# Generated by Django 6.0.4 on 2026-05-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('general_dentist', 'General Dentist'), ('oral_surgeon', 'Oral Surgeon'), ('orthodontist', 'Orthodontist'), ('cosmetic_dentist', 'Cosmetic Dentist'), ('prosthodontist', 'Prosthodontist'), ('pediatric_dentist', 'Pediatric Dentist'), ('emergency_dentist', 'Emergency Dentist'), ('endodontist', 'Endodontist')], max_length=100),
        ),
    ]
